<?php
/**
  * @author Rodrigo Silva
 * @copyright Copyright (c) 2023 Rodrigo Silva (https://github.com/SilRodrigo)
 * @package Rsilva_UserOnboarding
 */
/** @var \Rsilva\UserOnboarding\Block\Onboarding  $block */
?>

<?php if ($onboarding = $block->get()) : ?>
    <div class="introJs" data-bind="scope: 'loadIntro'"></div>

    <script type="text/x-magento-init">
        {
         "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "loadIntro": {
                        "component": "Rsilva_UserOnboarding/js/loadIntro",
                        "onboarding": <?= $onboarding->toJson() ?>
                    }
                }
            }
        }
    }
    </script>
<?php endif; ?>